-- 1. DROP CHILD TABLES FIRST
DROP TABLE IF EXISTS Dancer_Registration CASCADE;
DROP TABLE IF EXISTS Judge_Registration CASCADE;
DROP TABLE IF EXISTS Event CASCADE;
DROP TABLE IF EXISTS AddCodes CASCADE;

-- 2. DROP TABLES DEPENDING ON USER
DROP TABLE IF EXISTS Dancer CASCADE;
DROP TABLE IF EXISTS Judge CASCADE;
DROP TABLE IF EXISTS Organizer CASCADE;
DROP TABLE IF EXISTS Admins CASCADE;

-- 3. DROP COMPETITION AFTER ORGANIZER/JUDGE
DROP TABLE IF EXISTS Competition CASCADE;

-- 4. DROP USER LAST
DROP TABLE IF EXISTS "User" CASCADE;