CREATE TABLE "User" (
    User_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    First_name VARCHAR(50) NOT NULL,
    Last_name VARCHAR(50) NOT NULL,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Phone_number VARCHAR(20),
    Birthday DATE
);

CREATE TABLE Organizer (
    Organizer_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    User_ID INT REFERENCES "User"(User_ID) ON DELETE CASCADE,
    Recognized BOOLEAN DEFAULT FALSE,
    addcodeused VARCHAR(20) NOT NULL
);

CREATE TABLE Judge (
    Judge_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    User_ID INT REFERENCES "User"(User_ID) ON DELETE CASCADE,
    Highest_to_judge VARCHAR(50),
    ISTD_certified BOOLEAN DEFAULT FALSE,
    addcodeused VARCHAR(20) NOT NULL
);

CREATE TABLE Dancer (
    Dancer_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    User_ID INT REFERENCES "User"(User_ID) ON DELETE CASCADE,
    NDCA_number INT,
    NDCA_expiration DATE,
    Type VARCHAR(20)
);

CREATE TABLE Admins (
    Admin_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    User_ID INT REFERENCES "User"(User_ID) ON DELETE CASCADE
);

CREATE TABLE Competition (
    Competition_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    Organizer_ID INT REFERENCES Organizer(Organizer_ID) ON DELETE SET NULL,
    Location VARCHAR(100),
    Sanctioned BOOLEAN DEFAULT FALSE
);

CREATE TABLE AddCodes (
    Code_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Competition_ID INT REFERENCES Competition(Competition_ID) ON DELETE CASCADE,
    Code VARCHAR(20) UNIQUE NOT NULL,
    CodeType VARCHAR(20) NOT NULL CHECK (CodeType IN ('Organizer', 'Judge'))
);

CREATE TABLE Event (
    Event_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    Competition_ID INT REFERENCES Competition(Competition_ID) ON DELETE CASCADE,
    Title VARCHAR(100),
    Start_date_time TIMESTAMP,
    End_date_time TIMESTAMP,
    Rounds INT
);

CREATE TABLE Judge_Registration (
    JRegistration_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    Competition_ID INT REFERENCES Competition(Competition_ID) ON DELETE CASCADE,
    Judge_ID INT REFERENCES Judge(Judge_ID) ON DELETE CASCADE,
    JRegistration_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE Dancer_Registration (
    DRegistration_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    Competition_ID INT REFERENCES Competition(Competition_ID) ON DELETE CASCADE,
    Dancer_ID INT REFERENCES Dancer(Dancer_ID) ON DELETE CASCADE,
    Event_ID INT REFERENCES Event(Event_ID) ON DELETE CASCADE,
    DRegistration_date DATE DEFAULT CURRENT_DATE,
    Lead BOOLEAN
);